# Site settings
title: Sirisha Vemuri
email: vemuri.sirisha@gmail.com
url: https://sirisha-vemuri.github.io/portfolio/
description: "A UI/UX Designer's Portfolio"
keywords: "UI,UX"
skills: "User Experience, User Interface Designer with HCD"
meta_author: Vemuri Sirisha
currentstatus: 

# Google webmaster tools
google_verify: Ck6CS3ia--jBA9EsAKRI_0t83Uu5JytwX4sL-FZTy4Q

# GA tracking code

gatrackingcode: "GTM-WZQ6H29"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8d579c #503E2C #5f2d17 #395ab8 
  primary-rgb: 242, 219, 208 #217, 194, 184 #141, 87, 156 #"95, 44, 23"
  secondary: 2c3e50
  secondary-dark: 2c3e50

# Footer settings
footer:
  copyright: Sirisha Vemuri
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll
  - title: linkedin
    url: https://www.linkedin.com/in/sirisha-vemuri/

# Postal address (add as many lines as necessary)
address:
  - line: Melbourne
  - line: Victoria, Australia

# Credits content
credits: 'Site created and maintained by Chaithanya Gunturi'

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-loading-lazy  

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
